[tasks.stylua]
command = "stylua"
args = ["--config-path=./.stylua.toml", "-g", "*.lua", "--", "./src/lua"]

[tasks.rustfmt]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.codestyle]
run_task = [
    { name = "stylua" },
    { name = "rustfmt" }
]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.precommit]
dependencies = [
    "codestyle",
    "lint"
]
